// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8wEHcIysak9F3IXexfSxCYwefB7UPyZ4',
    appId: '1:61153841419:android:c7e61c81bd208c73a3d20e',
    messagingSenderId: '61153841419',
    projectId: 'brasa-app-dev',
    storageBucket: 'brasa-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAukeV0oU06X2xpP2ZjlRQAO4M4y_wzqTA',
    appId: '1:61153841419:ios:b1039945e8aebaa9a3d20e',
    messagingSenderId: '61153841419',
    projectId: 'brasa-app-dev',
    storageBucket: 'brasa-app-dev.firebasestorage.app',
    iosBundleId: 'com.example.brasaApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxsfsOi2Z2-QfoyMD8zJk1iqvID3BVIh4',
    appId: '1:61153841419:web:9b2f3c0a9564c4eea3d20e',
    messagingSenderId: '61153841419',
    projectId: 'brasa-app-dev',
    authDomain: 'brasa-app-dev.firebaseapp.com',
    storageBucket: 'brasa-app-dev.firebasestorage.app',
  );

}